name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
          cache-dependency-path: go.sum

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
